### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by Sil-B** [Vendic/EAVCleaner#2]
Error when using composer require 

![Schermafbeelding 2019-04-03 om 15 10 48](https://user-images.githubusercontent.com/15123701/55481605-0b017600-5623-11e9-87e5-a684381c5342.png)

**Comment by Tjitse-E** [comment]
The package is added to packagist now https://packagist.org/packages/hackathon/magento2-eavcleaner.
