### ISSUE TITLE
The helper "table" is not defined.

### ISSUE THREAD

**Issue by goldbr77** [Vendic/EAVCleaner#3]
In magento 2.3.1 I get the "The helper "table" is not defined." error when using the command eav:media:remove-unused 

The stated command removes ALL the images, not only the unused. :-(

Thanks

**Comment by boehsermoe** [comment]
Same error message :\

**Comment by Tjitse-E** [comment]
Fixed here https://github.com/Vendic/EAVCleaner/commit/de3e65eff2f857cfc791585ce42b95dc40e7ae69
