### ISSUE TITLE
There are no commands defined in the "eav:media" namespace

### ISSUE THREAD

**Issue by DaveSkirrow** [Vendic/EAVCleaner#7]
Hi there, 

When I try to run php bin/magento eav:media:remove-unused
I get the error  There are no commands defined in the "eav:media" namespace.

Could you help? I know the script works as I have run it in the past but I needed to restore to a previous backup and now I can't get it to run. 

Best regards,
Dave

**Comment by Tjitse-E** [comment]
@DaveSkirrow i've tested this on a fresh install of Magento 2.3.4 and all seems fine. Maybe you didn't install the module correctly? Is the module enabled (`module:status`)? Did try running `setup:upgrade` and `setup:di:compile`?

**Comment by DaveSkirrow** [comment]
Thanks! After running those commands and messing around a little it did eventually work on my test server, although I'm not sure what was causing it or what fixed it. I'll try again in the next few days on the main instance and let you know if I get stuck again,. 

Thanks again for your help. Much appreciated, and really useful script!

**Comment by Tjitse-E** [comment]
Okay great!
